apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: 381491860602.dkr.ecr.ap-northeast-2.amazonaws.com/mvp_custinfo_backend
  newName: 381491860602.dkr.ecr.ap-northeast-2.amazonaws.com/mvp_custinfo_backend
  newTag: "20240503150356"
