apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: 381491860602.dkr.ecr.ap-northeast-2.amazonaws.com/test_for_aws
  newName: 381491860602.dkr.ecr.ap-northeast-2.amazonaws.com/test_for_aws
  newTag: "20240514151157"
