apiVersion: v1
kind: Service
metadata:
  name:  baseinfo
  labels: # service monitor 의 selector 를 위하여 생성
    app: baseinfo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: baseinfo
  type: NodePort
